#!/bin/bash -x

chown -R ondemand-dex:ondemand-dex /etc/ood/dex
chmod -R 600 /etc/ood/dex
chmod 700 /etc/ood/dex

set -e

s6-setuidgid ondemand-dex /usr/sbin/ondemand-dex serve /etc/ood/dex/config.yaml
